export enum roles {
  ADMIN = "ADMIN",
  AGENT = "AGENT",
  COMPANY_ADMIN = "COMPANY_ADMIN",
  COMPANY_USER = "COMPANY_USER",
  DEVELOPER = "DEVELOPER",
  ADMINISTRATOR = "ADMINISTRATOR",
  MANAGER = "MANAGER",
  STAFF = "STAFF",
  CLIENT = "CLIENT",
}

export enum ClinicRole {
  CLINIC_ADMIN = "CLINIC_ADMIN",
  RECEPTIONIST = "RECEPTIONIST",
  NURSE = "NURSE",
  PROVIDER = "PROVIDER",
  LAB_TECH = "LAB_TECH",
  PHARMACIST = "PHARMACIST",
  ACCOUNTANT = "ACCOUNTANT",
}
