export enum roles {
  ADMIN = "ADMIN",
  AGENT = "AGENT",
  COMPANY_ADMIN = "COMPANY_ADMIN",
  COMPANY_USER = "COMPANY_USER",
  DEVELOPER = "DEVELOPER",
  ADMINISTRATOR = "ADMINISTRATOR",
  MANAGER = "MANAGER",
  STAFF = "STAFF",
  CLIENT = "CLIENT",
}
