-- AlterTable
ALTER TABLE "Items" ADD COLUMN     "isTaxable" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "taxCode" VARCHAR(1) NOT NULL DEFAULT 'A',
ADD COLUMN     "taxRate" DECIMAL(5,2) NOT NULL DEFAULT 0;
